language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
bioc_required: true
bioc_use_devel: true

r_packages:
  - covr
  - DT
  - pheatmap

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: AoSIHGx0+IQCoCeuCc3skINDMOoa2fDVUTdNNK4CjIkWfrWqMMXSOUc0txZdflWhwzijDF3ZzcMSJl2mHpK+yRTGT7GeaQ7djvmy2rypr4YnIttWm5APo3DXeKWFq+mfB/iXoA16D/Wu8gPgBijtd3BJntp2DeDGTYwAVtzGf52tZjbUZK29K3VdYeeLTq7h7HOkF104Z/yZ+ptTA+OWFSRsv/3vUK2gtzotM4ZkwdAOI7lQ1wktosVzMSjl6Fv8OJQVwqxpswY973C9e2dBzse2SUbF2vX1pM7R7UkQyAbFSTH3Yrcmz72SXM7U2uXhC57N5e9ZdhugUXagLK28oyREYWfnXDigmBkrBpbEThq0pGclShixl8HW5I/bYAeqF5w2TTD0H9gXpZJM7oq6TKQe3Lp6OtoF/GKACE+Bf8e14dcDsGg3GhtJoSPOdY7/zh1GeS5E7J1AmrxHlVdfodLeFtIN0RiMIg2VHHzW9/Bsks8JEzLafLPOuNumWFXF8ePR1SbTjETxxq8oET10F4wcQ2M5ewzlGTvKpjQtXIkBXzkggLJ5El51rMNRi8g5iixIhnQEx5wg9pB4DMq0n7e4lOZpCUoqrLeuHYvTE/epoetHNgj7g/EiEYBr3MkQ/WcuTvsDVT6IFjWD1b8UC1jbjDBowXYytiWjHcwCJJQ=

env:
  global:
    - _R_CHECK_TIMINGS_="0"
